name: Submit Stability Job On Official Branches

on:
  workflow_dispatch:
  schedule:
    - cron: "0 04 * * *" # Run at 04:00 UTC every day

permissions: read-all

jobs:
  GetBranches:
    name: Get Official Branches
    if: github.repository_owner == 'microsoft'
    runs-on: ubuntu-latest
    outputs:
      officialBranches: ${{ steps.getOfficialBranches.outputs.branchesJson }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Get Official Branches
        id: getOfficialBranches
        uses: microsoft/BCApps/.github/actions/GetGitBranches@97bd471a1cb85344f93e6e25e93f4ac01f84a274 # main
        with:
          include: "['releases/*']"

  SubmitStabilityJobs:
    name: "[${{ matrix.branch }}] Submit Stability Job"
    if: github.repository_owner == 'microsoft'
    runs-on: ubuntu-latest
    environment: Official-Build
    needs: GetBranches
    strategy:
      matrix:
        branch: ${{ fromJson(needs.GetBranches.outputs.officialBranches) }}
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Submit Stability Job
        env:
          GH_TOKEN: ${{ secrets.GHTOKENWORKFLOW }}
        uses: microsoft/BCApps/.github/actions/RunAutomation@97bd471a1cb85344f93e6e25e93f4ac01f84a274 # main
        with:
          automations: SubmitStabilityJob
          targetBranch: ${{ matrix.branch }}
